# Generated by Django 5.1 on 2024-09-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('classification_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Suffix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('suffix_status', models.CharField(max_length=10)),
            ],
        ),
    ]
