# Generated by Django 5.1 on 2024-09-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_classification_suffix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('prefix_status', models.CharField(max_length=10)),
            ],
        ),
    ]
