# Generated by Django 5.1 on 2024-09-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_formdata_field_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompAndBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=50)),
                ('choice2', models.CharField(max_length=50)),
                ('choice3', models.CharField(max_length=50)),
                ('choice4', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='FormData',
            new_name='Series',
        ),
    ]
