# Generated by Django 5.1 on 2024-10-01 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('storage_type', models.CharField(max_length=10)),
                ('dimension', models.CharField(max_length=20)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.plant')),
            ],
        ),
    ]
